# Generated by Django 5.1.3 on 2024-11-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('WIP', 'Work in Progress'), ('DONE', 'Done'), ('CLOSED', 'Closed')], default='WIP', max_length=20),
        ),
    ]
